### ISSUE TITLE
Make it possible to serve external resources to protect the users privacy

### ISSUE THREAD

**Issue by maralorn** [srid/neuron#287] opened 2020-07-14 18:02 UTC
Loading fonts or javascript from external sources is an anti-feature for privacy aware users.

We should implement a way to download the sources at html generation time and serve them from the same document root.

**Comment by srid** [comment] 2020-07-14 19:50
Duplicate of #96

**Closed by srid** 2020-07-14 19:50 UTC

**Comment by maralorn** [comment] 2020-07-14 21:43
Sorry, for the duplicate, I had searched by the wrong keywords.
