### ISSUE TITLE
problem with using hashes anywhere in notes for tags

### ISSUE THREAD

**Issue by muralikodali** [srid/neuron#464] opened 2020-11-12 15:45 UTC
using hash (#) to tag anywhere in the notes is a convenient feature. but, it also gives headache in some other scenarios. I am getting weird tags in neuron tag searching like **#RRGGBB (colors), #DIV, #-** etc. I request you to give a thought about it.

**Comment by srid** [comment] 2020-11-12 17:01
Duplicate of #459

**Closed by srid** 2020-11-12 17:01 UTC
