### ISSUE TITLE
Title should not be duplicated

### ISSUE THREAD

**Issue by babygau** [srid/neuron#416] opened 2020-09-28 09:46 UTC
Hi,

I think title should not be duplicated in case you use both title in front matter and markdown header.
<img width="1135" alt="Screen Shot 2020-09-28 at 7 43 28 pm" src="https://user-images.githubusercontent.com/1514823/94417161-122b2500-01c3-11eb-9407-1c8faf3c3ab3.png">

Example to reproduce

```
---
title: macOs Keyboard Layout
date: ...
---

# macOs Keyboard Layout
```

**Comment by srid** [comment] 2020-09-28 13:33
Duplicate of #412 ?

For now, just remove the title front matter.

**Comment by babygau** [comment] 2020-09-28 15:45
Thank you

**Closed** 2020-10-07 22:30 UTC
