### ISSUE TITLE
support citations via pandoc-citeproc

### ISSUE THREAD

**Issue by boutil** [srid/neuron#405] opened 2020-09-18 14:18 UTC
Hi,
Would it be possible to implement support for bibliography/citations using pandoc-citeproc?
This would allow to make references to scientific articles or books in zettels, which would be useful for research projects.

Thanks in advance.

**Comment by srid** [comment] 2020-09-18 16:46
@boutil Is your request a duplicate of #134 ?

**Comment by srid** [comment] 2020-09-18 16:47
Yup, looks like it - closing as dup.

**Closed by srid** 2020-09-18 16:47 UTC

**Comment by boutil** [comment] 2020-09-18 17:10
Yes indeed, it is the same. The search I did among the open issues was not thorough enough.

By the way, great project!
