### ISSUE TITLE
Building neuron for aarch64 ?

### ISSUE THREAD

**Issue by 573** [srid/neuron#66] opened 2020-04-07 12:24 UTC
I love to use neuron and do so on my laptop already.
What would be extra nice is to be able to use on my smartphone as well (where I have [nix-on-droid](https://github.com/t184256/nix-on-droid) installed already), so my plan was to:

* cross-build it on my laptop
* by using copy-closure or nix-copy transfer the built neuron closure to my smartphone

What others have [found out](https://discourse.nixos.org/t/best-practices-for-building-aarch64-linux-pkgs-on-a-x86-64-linux-system/1697/6) and I have tested so far is that it is possible to - taking clay as an example as it builds:

```
nix-build -E 'with import <nixpkgs> {}; pkgsCross.aarch64-multiplatform-musl.haskellPackages.ghcWithPackages (p: [p.clay])'
nix-build "<nixpkgs>" -A pkgsCross.aarch64-multiplatform-musl.haskellPackages.clay
```
Are there chances to make the neuron build possible for any of the `pkgsCross.aarch64-*` targets as well ?

**Comment by srid** [comment] 2020-04-07 16:26
@573 I don't know much about cross-building, but a PR is always welcome. Also see #45, which may be relevant.

**Comment by srid** [comment] 2020-04-07 21:42
Oh and I'm planning to make a release to hackage soon. That should get it into stackage and nixpkgs.

**Comment by srid** [comment] 2020-05-24 01:02
Thanks to @maralorn - neuron is now on nixpkgs, however note that it is an old version. `nix-shell -p haskellPackages.neuron`.

**Comment by srid** [comment] 2020-07-18 17:40
@573 Have you managed to build neuron on aarch64?

Here's somebody else who is trying it: https://lobste.rs/s/7e7l03/how_i_publish_notes#c_vwmf0h

**Comment by 573** [comment] 2020-07-30 09:26
I would like to build that on my phone as the latter is prepared to use a remote builder now.
How would I utilize the nixpkgs version ?
For now I have in my home-manager config:

```
# ~/.config/nixpkgs/program/haskell/default.nix
let unstable = import (fetchTarball https://nixos.org/channels/nixos-unstable/nixexprs.tar.xz) {};
in { pkgs, config, ... }:
{
  home.packages = with unstable.pkgs.haskellPackages; [
    neuron
  ];
}
```

and
```
# ~/.config/nixpkgs/home.nix
{ pkgs ? import <nixpkgs> {},... }:
{
  imports = [ ./program/haskell ];
}
```

Build still fails though, see [log](http://ix.io/2sG2).
On [hydra](https://hydra.nixos.org/job/nixpkgs/trunk/haskellPackages.neuron.aarch64-linux/all) there also seems to be no green build yet.

**Comment by maralorn** [comment] 2020-07-30 12:58
@573 that is definitely a nixpkgs issue as our expression doesn't touch anything that affects the compilation of ghc.

Someone needs to open an issue with nixpkgs if that hasn't happened yet.

Besides that you could try if it works to use 8.8.3 instead. You can switch that in the default.nix by replacing hackagePackages with the appropriate specific version.

**Comment by 573** [comment] 2020-07-31 20:02
I tried again with ghc883 and the build although very long lasting (> 24hs) seems to do fine.
Currently there was a problem building [jsaddle-dom](http://ix.io/2sNP) with my remote builder.
I keep you updated.

**Comment by 573** [comment] 2020-08-01 16:35
No chance, even with [profiling disabled](http://ix.io/2sS1)

```
(justStaticExecutables (dontCheck (doJailbreak jsaddle-dom)))
```

**Comment by 573** [comment] 2020-08-04 06:02
I thought I am trying and building a [bundle](https://github.com/573/neuron/blob/master/.github/workflows/aarch64.yaml) as suggested by @srid [here](https://lobste.rs/s/7e7l03/how_i_publish_notes#c_8rgasd).
But am not really [getting any step forward](https://github.com/573/neuron/releases/download/nightly/neuron-aarch64-bundle) as the bundle seems to be identical to the linux one and I can indeed run it on a x64 machine as opposed to an aarch64 one.
Any hints pls ?

**Comment by maralorn** [comment] 2020-08-04 09:36
@573 I still believe your best bet is fixing (or getting someone to fix) the ghc884 build in nixpkgs. It might not help, but you should really try opening an issue in nixpkgs, if there isn't one. I would do it but I am limited to my phones keyboard right now.

**Comment by 573** [comment] 2020-08-04 09:50
@maralorn I guess I progressed a tiny step as I have the same error [on github-actions](https://github.com/573/neuron/runs/944221870) [now](https://github.com/573/neuron/commit/282efd367d37addba8ecdbdd9e2f50c1fbf74eaf) as on my phone [earlier](http://archive.vn/GVcZa).
What still bothers me is [this line](https://github.com/573/neuron/runs/944221870#step:7:362):
```
qemu: Unsupported syscall: 276
```
You're right in pointing to ghc884.
To have a workaround I could still try to let the build use ghc883 for the sake of having an aarch64 bundle.

**Comment by 573** [comment] 2020-08-05 09:13
I will continue my experiments here: https://github.com/573/neuron (https://github.com/573/neuron/tree/add-workflow-aarch64).

**Comment by maralorn** [comment] 2020-08-16 14:49
@573 Have you tried building neuron on latest master? According to https://github.com/NixOS/nixpkgs/issues/94649 this should be fixed.

**Comment by 573** [comment] 2020-08-19 13:18
@maralorn this is great news tryin asap. sorry for the delay.

**Comment by 573** [comment] 2020-08-20 09:06
@maralorn I built against the master of neuron as of yesterday and got [this error](http://ix.io/2uHH) (http://archive.vn/wip/FWxBg)

**Comment by maralorn** [comment] 2020-08-20 11:17
@573 Is that error reproducible?

**Comment by maralorn** [comment] 2020-08-20 11:35
I am sorry, I am out of my depth here. You have an issue with jira-wiki-markup-1.3.2 not building with an error that is either environmental e.g. OOM or something or a segfault. I have a few puzzle points here, but I am not sure what to make of it.

neuron on aarch64 is right now broken on master because some dep has a bug on aarch64 and fails the test: https://hydra.nixos.org/build/125390340

Now jira-wiki-markup-1.3.2 only gets compiled as part of the neuron job, because of newer pandoc-types, etc. But jiri-wiki-markup-1.2.1 builds succesfully on aarch64 apparently: https://hydra.nixos.org/eval/1607860?filter=jira-wiki-markup&compare=1607838&full=#tabs-still-fail

Sadly I don‘t use nix on any aarch64 so I don‘t think I can help with this much more.

**Comment by 573** [comment] 2020-08-20 13:46
@maralorn I was indeed building locally:
```
nix-build -j4 --option system aarch64-linux --option sandbox false --extra-platforms aarch64-linux --expr 'import ./shell.nix { doCheck = false; }'
```
with my master in sync with upstream srid/neuron repo.

The reason I chose a local machine is that github-actions allow for certain amount of minutes for a job and one single build currently exceeds this.

With setting up builds on hydra I have no experience.

**Comment by srid** [comment] 2020-10-09 19:12
There is now a `static.nix` which is used to build static binaries on Linux. Maybe with a few changes that would also work for aarch64?

Try: `nix-build static.nix`.

**Comment by 573** [comment] 2020-10-12 12:05
@srid that is great news !
Still get some [errors](https://paste.c-net.org/2813bcb5-5d45-de3d-39f9-5f6a15f79474) though (testsuite for GNU coreutils 8.31 is attempted and IDK how to disable this).

**Comment by 573** [comment] 2020-10-14 09:03
FYI, the [last 5K](https://paste.c-net.org/c4e52122-00b4-ba3d-602a-fb2b3808ca0c) lines of the failing build.

**Comment by 573** [comment] 2020-11-04 10:52
Shameless X-marketing, the [nix-on-droid wiki](https://github.com/t184256/nix-on-droid/wiki/Same-machine-remote-builder-how-to) now contains some more hints on installing NixOS in a (local) qemu vm to serve as a builder for aarch64 !

**Closed** 2020-11-10 23:06 UTC
Labels: discussion
